openapi: 3.0.0
info:
  title: HTM Token Transaction Count API
  description: API to get the transaction count for the HTM-f51d55 token.
  version: 1.0.0
servers:
  - url: https://api.elrond.com
paths:
  /tokens/HTM-f51d55/transactions/count:
    get:
      summary: Get transaction count for HTM-f51d55 token
      parameters:
        - name: status
          in: query
          required: true
          description: The status of the transactions (e.g., success)
          schema:
            type: string
            enum:
              - success
              - pending
              - failed
      responses:
        '200':
          description: Successful response with transaction count
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 12345

